const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/adminNotification.controller');
const auth = require('../middlewares/auth.middleware');

// Admin-only doctor alerts management
router.post('/admin/doctor-alerts', auth.verifyToken, auth.requireAdmin, ctrl.createDoctorAlert);
router.post('/admin/doctor-alerts/auto-generate', auth.verifyToken, auth.requireAdmin, ctrl.autoGenerateDoctorAlerts);
router.get('/admin/doctor-alerts', auth.verifyToken, auth.requireAdmin, ctrl.listDoctorAlerts);
router.get('/admin/doctor-alerts/stats', auth.verifyToken, auth.requireAdmin, ctrl.getDoctorAlertStats);

module.exports = router;
